apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: jvm-build-suite-component-arkcci
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: jvm-build-suite-component-arkcci
    app.kubernetes.io/part-of: jvm-build-suite-application-igjv
  name: jvm-build-suite-component-arkcci
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: jvm-build-suite-component-arkcci
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: jvm-build-suite-component-arkcci
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/jvm-build-jfgf-tenant/jvm-build-suite-application-igjv/jvm-build-suite-component-arkcci@sha256:a7d92101fbad7c6414ce07bb99f506fd061d7851c29243eb4683c6890ad1856e
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
